### ISSUE TITLE
CUDA out of memory attempting to generate video with 16GB GPU

### ISSUE THREAD

**Issue by rossoe** [trianglesplatting/triangle-splatting#20]
I'm in Ubuntu, having completed **train.py**, and it all seemed to complete ok, I used **render.py** and I can see ground truth vs a bunch of renders. I've also successfully run **create_off.py**.

But when I try and create a video with: 
`python create_video.py -m /home/Data/Output_model/`

It stops with the following error:

> torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.00 MiB. GPU 0 has a total capacity of 15.69 GiB of which 21.94 MiB is free. Including non-PyTorch memory, this process has 14.95 GiB memory in use. Of the allocated memory 14.63 GiB is allocated by PyTorch, and 39.59 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. 

I tried the `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` and that didn't help.

I have a 16GB GPU and it looks like usage is at  762MiB / 16376MiB

I tried clearing torch cache with  `torch.cuda.empty_cache()`

It was a fairly large outdoor scene with 133 camera positions.

Any other tricks I'm missing?

**Comment by lif314** [comment]
Same issue with RTX 3090 (24 GB GPU)

**Comment by rossoe** [comment]
Quick fix I found last night, in this file:
`/triangle-splatting/scene/__init__.py`

Change scale to **1.5** here:

`def __init__(self, args : ModelParams, triangles : TriangleModel, init_opacity, init_size, nb_points, set_sigma, no_dome=False, load_iteration=None, shuffle=True, resolution_scales=[1.5]):`

and also here:

```
    def getTrainCameras(self, scale=1.5):
        return self.train_cameras[scale]

    def getTestCameras(self, scale=1.5):
        return self.test_cameras[scale]
```

That only consumed 12.5GB on my GPU.

**Comment by brownbeard12** [comment]
Thank you, it worked for me using `2.0`.

**Comment by lif314** [comment]
@rvandeghen Hello, here is my test dataset.

https://drive.google.com/file/d/1Bo01ajrxnuLzgeEwlGdU46-zqBBvPPDt/view?usp=sharing

**Comment by rvandeghen** [comment]
Hi @lif314,

I was able to train, render, and make a video. Here is a snapshot from meshlab.

From my point of view, the "mesh" version of the triangle soup is as expected.

![Image](https://github.com/user-attachments/assets/834731b8-d260-4ef4-b17c-7c6a14581da5)

If you encounter memory issues again, I suggest you to use `-r 2` in the command line.

I also think that your images are quite noisy (motion blur I guess), which is not suitable for high quality results.

Let me know if you still have questions/issues.

Renaud

**Comment by lif314** [comment]
@rvandeghen Thank you very mush! I will try again.
